export const GET_ALL_PROMOTIONS_API_URL = "promo";
export const PROMOTION_TITLE = "Promociones";
export const MAX_PROMOTIONS_PER_SLIDE_MOBILE = 1.3;
export const MAX_PROMOTIONS_PER_SLIDE_TABLET = 3;
export const MAX_PROMOTIONS_PER_SLIDE_DESKTOP = 4.3;
export const PROMOTION_SLIDE_SPACE_BETWEEN_ITEMS_MOBILE = 4;
export const PROMOTION_SLIDE_SPACE_BETWEEN_ITEMS_DESKTOP = 0;
export const PROMOTIONS_LEGAL_AGE_REQUIRED = ["140", 140, "132", 132];
